ansible_connection: amazon.aws.aws_ssm
ansible_aws_ssm_region: eu-west-3
ansible_aws_ssm_bucket_name: aws-s3-soc-lab-253490786526-eu-west-3-an
ansible_shell_type: sh
ansible_shell_executable: /bin/sh
ansible_python_interpreter: /usr/bin/python3
elasticsearch_host: 10.0.x.x
elasticsearch_port: 9200
kibana_port: 5601
vault_url: "https://vault.lab.local:8200"
filebeat_role_name: filebeat
kibana_role_name: kibana
elastic_role_name: elastic