- name: Installer filebeat
  ansible.builtin.apt:
    name: filebeat
    state: present

- name: Activer module Docker Filebeat si pas déjà fait
  ansible.builtin.command: filebeat modules enable docker
  become: yes
  register: docker_module
  changed_when: "'Enabled' in docker_module.stdout"

- name: Create cert dir
  ansible.builtin.file:
    path: /etc/filebeat/certs
    state: directory
    owner: filebeat
    group: filebeat
    mode: "0700"

- name: Copy filebeat cert
  ansible.builtin.copy:
    src: "/tmp/certs/filebeat/filebeat.crt"
    dest: /etc/filebeat/certs/filebeat.crt
    owner: filebeat
    group: filebeat
    mode: "0644"

- name: Copy filebeat key
  ansible.builtin.copy:
    src: "/tmp/certs/filebeat/filebeat.key"
    dest: /etc/filebeat/certs/filebeat.key
    owner: filebeat
    group: filebeat
    mode: "0600" 

- name: Copy CA
  ansible.builtin.copy:
    src: "/tmp/pki/ca.crt"
    dest: /etc/filebeat/certs/ca.crt
    owner: filebeat
    group: filebeat
    mode: "0644"

- name: Wait for Elasticsearch
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200"
    method: GET
    validate_certs: true
    ca_path: /etc/filebeat/certs/ca.crt
  register: elastic_status
  until: elastic_status.status == 200
  retries: 30
  delay: 5

- name: Create Filebeat keystore
  ansible.builtin.command:
    cmd: /usr/share/filebeat/bin/filebeat keystore create
    creates: /etc/filebeat/filebeat.keystore

- name: Get Filebeat API key from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: filebeat_api_key
  register: filebeat_api_key_secret
  no_log: true

- name: Add Filebeat API key to keystore
  ansible.builtin.command:
    cmd: >
      /usr/share/filebeat/bin/filebeat keystore add
      ES_API_KEY --stdin 
  stdin: "{{ filebeat_api_key_secret.data.data.api_key }}"
  register: keystore_apikey
  changed_when: keystore_apikey.rc == 0
  failed_when: keystore_apikey.rc != 0 and 'already exists' not in keystore_apikey.stderr
  no_log: true
  notify: restart filebeat

- name: Get kibana password from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: kibana
  register: kibana_secret
  no_log: true

- name: Add Kibana password to Filebeat keystore
  ansible.builtin.command:
    cmd: >
      /usr/share/filebeat/bin/filebeat keystore add
      KIBANA_PASSWORD --stdin
  stdin: "{{ kibana_secret.data.data.kibana_password }}"
  no_log: true
  register: keystore_kibana
  changed_when: keystore_kibana.rc == 0
  failed_when: keystore_kibana.rc != 0 and 'already exists' not in keystore_kibana.stderr
  notify: restart filebeat
   
- name: Activer parsing logs 
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    validate: '/usr/bin/filebeat -t -c %s'
  notify: restart filebeat

- name: Start Filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: started
    enabled: true