- name: Create cert dir
  ansible.builtin.file:
    path: /etc/elasticsearch/certs
    state: directory
    owner: elasticsearch
    group: elasticsearch
    mode: "0700"

- name: Copy cert
  ansible.builtin.copy:
    dest: /etc/elasticsearch/certs/elasticsearch.crt
    content: >-
      {{ cert_results.results
         | selectattr('item.name', 'equalto', 'elasticsearch')
         | map(attribute='data.data.crt')
         | first }}
    owner: elasticsearch
    group: elasticsearch
    mode: "0644"
  delegate_to: localhost
  no_log: true
  notify: restart elasticsearch
  

- name: Copy key
  ansible.builtin.copy:
    dest: /etc/elasticsearch/certs/elasticsearch.key
    content: >-
      {{ cert_results.results
         | selectattr('item.name', 'equalto', 'elasticsearch')
         | map(attribute='data.data.private_key')
         | first }}
    owner: elasticsearch
    group: elasticsearch
    mode: "0600"
  delegate_to: localhost
  no_log: true
  notify: restart elasticsearch

- name: Copy CA
  ansible.builtin.copy:
    src: "/tmp/pki/ca.crt"
    dest: /etc/elasticsearch/certs/ca.crt
    owner: elasticsearch
    group: elasticsearch
    mode: "0644"
  notify: restart elasticsearch

- name: Configure Elasticsearch
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: Enable Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true