# security.yml
- name: Collecter l'état des services
  ansible.builtin.service_facts:

- name: Get secrets from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: elastic
  register: elastic_secret
  delegate_to: localhost
  ignore_errors: true
  no_log: true

- name: Fail if secret missing
  ansible.builtin.fail:
    msg: "Elastic password missing in Vault"
  when: elastic_secret is failed

- name: Démarrer Elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    #state: "{{ 'restarted' if ansible_facts.services['elasticsearch.service'].state | default('') == 'running' else 'started' }}"
    state: restarted
    enabled: true

- name: Attendre qu'Elasticsearch soit prêt
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200"
    validate_certs: true
    ca_path: /etc/elasticsearch/certs/ca.crt
  register: es_up
  until: es_up.status in [200, 401]
  retries: 10
  delay: 10

- name: Vérifier si les credentials Vault sont déjà valides
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200"
    method: GET
    user: elastic
    password: "{{ elastic_secret.data.data.elastic_password }}"
    validate_certs: true
    ca_path: /etc/elasticsearch/certs/ca.crt
  register: auth_check
  ignore_errors: true
  no_log: true

- name: Initialiser le mot de passe elastic (bootstrap)
  ansible.builtin.command:
    cmd: >
      /usr/share/elasticsearch/bin/elasticsearch-reset-password
      -u elastic --batch --url https://{{ elasticsearch_host }}:9200
  environment:
    ES_JAVA_OPTS: ""
  register: reset_result
  changed_when: reset_result.rc == 0
  no_log: true
  when: auth_check.status  | default(0) == 401

- name: Extraire le mot de passe bootstrap
  ansible.builtin.set_fact:
    bootstrap_password: "{{ reset_result.stdout | regex_search('New value: (.+)', '\\1') | first }}"
  when: auth_check.status | default(0) == 401
  no_log: true

- name: Assert bootstrap password extracted
  ansible.builtin.assert:
    that: bootstrap_password | length > 0
    fail_msg: "Impossible d'extraire le mot de passe bootstrap"
  when: auth_check.status | default(0) == 401

- name: Set elastic password via API
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_security/user/elastic/_password"
    method: POST
    user: elastic
    password: "{{ bootstrap_password }}"
    body_format: json
    body:
      password: "{{ elastic_secret.data.data.elastic_password }}"
    validate_certs: true
    ca_path: /etc/elasticsearch/certs/ca.crt
  no_log: true
  when: auth_check.status | default(0) == 401