- name: Create cert directories
  ansible.builtin.file:
    path: "/tmp/certs/{{ item.name }}"
    state: directory
    mode: "0700"
  loop: "{{ services }}"

- name: Create CA directory
  ansible.builtin.file:
    path: /tmp/pki
    state: directory
    mode: "0755"

- name: Get CA from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: pki/ca
  register: ca_data
  no_log: true

- name: Generate certificates for services
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: "{{ pki_path }}"
    role_name: "{{ pki_role_name }}"
    common_name: "{{ item.cn }}"
    alt_names: "{{ item.dns | default([item.cn]) | join(',') }}"
    ip_sans: >-
      {{
        (['127.0.0.1'] +
        ([hostvars[groups[item.host][0]].ansible_host]
          if (groups[item.host] is defined and groups[item.host] | length > 0)
          else [])
        ) | join(',')
      }}
    ttl: "{{ cert_ttl }}"
  loop: "{{ services }}"
  register: cert_results
  no_log: true

- name: Save certificates
  ansible.builtin.copy:
    dest: "/tmp/certs/{{ item.item.name }}/{{ item.item.name }}.crt"
    content: "{{ item.data.certificate }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ cert_results.results }}"
  no_log: true

- name: Save private keys
  ansible.builtin.copy:
    dest: "/tmp/certs/{{ item.item.name }}/{{ item.item.name }}.key"
    content: "{{ item.data.private_key }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ cert_results.results }}"
  no_log: true

- name: Save CA
  ansible.builtin.copy:
    dest: /tmp/pki/ca.crt
    content: "{{ ca_data.data.data.certificate }}"
    mode: "0644"
  no_log: true