collections:
  - name: community.hashi_vault
  - name: community.general
  - name: ansible.posix
###--à installer avec ansible-galaxy collection install -r requirements.yml dans control node--
###-- commande pip install hvac pour modules vault