- name: Get elastic secret from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: elastic
  delegate_to: localhost
  register: elastic_secret
  no_log: true

- name: check if kibana cert exists
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: tmp/certs/kibana/kibana.crt
  delegate_to: localhost
  register: existing_cert
  ignore_errors: true
  no_log: true

- name: Récupérer Cert existante
  ansible.builtin.set_fact:
    kibana_cert:
      data:
        data:
          certificate: "{{ existing_cert.data.data.certificate }}"
          private_key: "{{ existing_cert.data.data.private_key }}"
  when: existing_cert.data is defined

- name: Vérifier expiration des certificats existants
  ansible.builtin.shell: |
    echo "{{ existing_cert.data.data.certificate }}" | \
    openssl x509 -checkend 604800 -noout
  register: cert_expiry
  failed_when: false
  changed_when: false
  when: existing_cert.data is defined

- name: Generate kibana cert from Vault
  community.hashi_vault.vault_pki_generate_certificate:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: pki
    role_name: "{{ kibana_role_name }}"
    common_name: kibana.lab.local
    alt_names: kibana.lab.local,kibana
  when: >
    existing_cert.data is not defined or
    (cert_expiry.rc | default(1)) != 0
  delegate_to: localhost
  register: kibana_cert
  no_log: true

- name: Résoudre le cert final
  ansible.builtin.set_fact:
    final_kibana_cert:
      certificate: >-
        {{ kibana_cert.data.certificate
           if kibana_cert is not skipped
           else existing_cert.data.data.certificate }}
      private_key: >-
        {{ kibana_cert.data.private_key
           if kibana_cert is not skipped
           else existing_cert.data.data.private_key }}
  no_log: true

- name: copy kibana cert
  ansible.builtin.copy:
    dest: /etc/kibana/certs/kibana.crt
    content: "{{ final_kibana_cert.certificate }}"
    owner: kibana
    group: kibana
    mode: "0644"
  no_log: true
  notify: restart kibana

- name: copy kibana key
  ansible.builtin.copy:
    dest: /etc/kibana/certs/kibana.key
    content: "{{ final_kibana_cert.private_key }}"
    owner: kibana
    group: kibana
    mode: "0644"
  no_log: true
  notify: restart kibana

- name: Store generated cert in Vault
  community.hashi_vault.vault_kv2_write:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: tmp/certs/kibana/kibana.crt
    data:
      certificate: "{{ final_kibana_cert.certificate }}"
      private_key: "{{ final_kibana_cert.private_key }}"
  delegate_to: localhost
  when: >
    existing_cert.data is not defined or
    (cert_expiry.rc | default(1)) != 0
  no_log: true

- name: Lire le CA depuis Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: tmp/pki/ca.crt
  delegate_to: localhost
  register: ca_cert

- name: Copy CA vers kibana
  ansible.builtin.copy:
    dest: /etc/kibana/certs/ca.crt
    content: "{{ ca_cert.data.data.certificate }}"
    owner: kibana
    group: kibana
    mode: "0644"
  notify: restart kibana
  no_log: true

- name: Create Kibana keystore
  ansible.builtin.command:
    cmd: /usr/share/kibana/bin/kibana-keystore create
    creates: /etc/kibana/kibana.keystore

- name: Get kibana password from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: kibana
  delegate_to: localhost
  register: kibana_secret
  no_log: true

- name: Wait for Elasticsearch
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_cluster/health"
    method: GET
    user: elastic
    password: "{{ elastic_secret.data.data.elastic_password }}"
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: es_health
  until: >
    es_health.status == 200 and
    es_health.json.status in ['yellow', 'green']
  retries: 30
  delay: 5

- name: Vérifier si le mot de passe kibana_system est déjà correct
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_security/user/kibana_system"
    method: GET
    user: kibana_system
    password: "{{ kibana_secret.data.data.kibana_password }}"
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: kibana_auth_check
  ignore_errors: true
  no_log: true

- name: Set kibana_system password
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_security/user/kibana_system/_password"
    method: POST

    user: elastic
    password: "{{ elastic_secret.data.data.elastic_password }}"
    force_basic_auth: true

    body_format: json
    body:
      password: "{{ kibana_secret.data.data.kibana_password }}"

    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
    status_code: 200
  no_log: true
  when: kibana_auth_check is failed

- name: Add kibana_system password to keystore
  ansible.builtin.command:
    cmd: >
      /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
      --stdin
      --force
    stdin: "{{ kibana_secret.data.data.kibana_password }}"
  no_log: true
  register: keystore_add
  changed_when: kibana_auth_check is failed
  notify: restart kibana

- name: configurer kibana vers elasticsearch
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana