- name: Get elastic secret from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: elastic
  register: elastic_secret
  no_log: true

- name: Installer kibana
  ansible.builtin.apt:
    name: kibana
    state: present

- name: Create cert dir
  ansible.builtin.file:
    path: /etc/kibana/certs
    state: directory
    owner: kibana
    group: kibana
    mode: "0700"

- name: Copy kibana cert
  ansible.builtin.copy:
    src: "/tmp/certs/kibana/kibana.crt"
    dest: /etc/kibana/certs/kibana.crt
    owner: kibana
    group: kibana
    mode: "0644"

- name: Copy Kibana key
  ansible.builtin.copy:
    src: "/tmp/certs/kibana/kibana.key"
    dest: /etc/kibana/certs/kibana.key
    owner: kibana
    group: kibana
    mode: "0600"

- name: Copy CA
  ansible.builtin.copy:
    src: "/tmp/pki/ca.crt"
    dest: /etc/kibana/certs/ca.crt
    owner: kibana
    group: kibana
    mode: "0644"

- name: Create Kibana keystore
  ansible.builtin.command:
    cmd: /usr/share/kibana/bin/kibana-keystore create
    creates: /etc/kibana/kibana.keystore

- name: Get kibana password from Vault
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    token: "{{ vault_token }}"
    engine_mount_point: secret
    path: kibana
  register: kibana_secret
  no_log: true

- name: Wait for Elasticsearch
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_cluster/health"
    method: GET
    user: elastic
    password: "{{ elastic_secret.data.data.elastic_password }}"
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: es_health
  until: es_health.status == 200
  retries: 30
  delay: 5

- name: Vérifier si le mot de passe kibana_system est déjà correct
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_security/user/kibana_system"
    method: GET
    user: kibana_system
    password: "{{ kibana_secret.data.data.kibana_password }}"
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: kibana_auth_check
  ignore_errors: true
  no_log: true

- name: Set kibana_system password
  ansible.builtin.uri:
    url: "https://{{ elasticsearch_host }}:9200/_security/user/kibana_system/_password"
    method: POST

    user: elastic
    password: "{{ elastic_secret.data.data.elastic_password }}"
    force_basic_auth: true

    body_format: json
    body:
      password: "{{ kibana_secret.data.data.kibana_password }}"

    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
    status_code: 200
  no_log: true
  when: kibana_auth_check is failed

- name: Add kibana_system password to keystore
  ansible.builtin.command:
    cmd: >
      /usr/share/kibana/bin/kibana-keystore add elasticsearch.password
      --stdin
      --force
    stdin: "{{ kibana_secret.data.data.kibana_password }}"
  no_log: true
  register: keystore_add
  changed_when: keystore_add.rc == 0
  notify: restart kibana

- name: configurer kibana vers elasticsearch
  ansible.builtin.template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

- name: Activer kibana
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: true

- name: flush_handlers
  ansible.builtin.meta: flush_handlers
    
- name: Vérifier Kibana
  ansible.builtin.uri:
    url: "https://localhost:5601/api/status"
    method: GET
    return_content: true
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: kibana_status
  until: kibana_status.status == 200
  retries: 30
  delay: 5
