- name: Activer kibana
  ansible.builtin.systemd:
    name: kibana
    state: started
    enabled: true

- name: flush_handlers
  ansible.builtin.meta: flush_handlers
    
- name: Vérifier Kibana
  ansible.builtin.uri:
    url: "https://localhost:5601/api/status"
    method: GET
    return_content: true
    validate_certs: true
    ca_path: /etc/kibana/certs/ca.crt
  register: kibana_status
  until: kibana_status.status == 200
  retries: 30
  delay: 5